### ISSUE TITLE
PyPI installation doesn't work

### ISSUE THREAD

**Issue by yibeichan** [nipype/nipype2pydra#5]
Hi @tclose , Dorota and I tried to install nipype2pydra through PyPI, but couldn't make it work

```
pip install nipype2pydra
 
ERROR: Could not find a version that satisfies the requirement nipype2pydra (from versions: none)
ERROR: No matching distribution found for nipype2pydra
```

**Comment by tclose** [comment]
Hi @yibeichan, yes sorry the README instructions are ahead of the game a little. I haven't made an initial release yet. I have just changed them to point to the github repo although you will probably want to install a dev version with `pip install -e <path-to-your-repo-clone>` for now

**Comment by yibeichan** [comment]
oh thank you; yes, `pip install -e <path-to-your-repo-clone>` works!
